# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Downloader(object):
    def setupUi(self, Downloader):
        Downloader.setObjectName("Downloader")
        Downloader.resize(360, 800)
        Downloader.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Downloader)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.urlEdit = QtWidgets.QLineEdit(Downloader)
        self.urlEdit.setObjectName("urlEdit")
        self.horizontalLayout.addWidget(self.urlEdit)
        self.pasteButton = QtWidgets.QToolButton(Downloader)
        self.pasteButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/粘贴.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pasteButton.setIcon(icon)
        self.pasteButton.setObjectName("pasteButton")
        self.horizontalLayout.addWidget(self.pasteButton)
        self.downloadButton = QtWidgets.QToolButton(Downloader)
        self.downloadButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/下载.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.downloadButton.setIcon(icon1)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout.addWidget(self.downloadButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.infoWidget = QtWidgets.QListWidget(Downloader)
        self.infoWidget.setStyleSheet("QListView \n"
"{\n"
"      show-decoration-selected: 1;\n"
"}\n"
" \n"
"QListView::item:alternate \n"
"{\n"
"      background: #EEEEEE;\n"
"}\n"
" \n"
"QListView::item:selected \n"
"{\n"
"      border: 1px solid #d4d4d4;\n"
"}\n"
" \n"
"QListView::item:selected:!active \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.0284091, x2:0, y2:0, stop:0.278607 rgba(252, 210, 171, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
" \n"
"QListView::item:selected:active\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.0284091, x2:0, y2:0, stop:0.278607 rgba(245, 252, 171, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
" \n"
"QListView::item:hover\n"
"{\n"
"      background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                  stop: 0 #FAFBFE, stop: 1 #DCDEF1);\n"
"}\n"
"\n"
"//适用于开启交替颜色\n"
"QListWidget#listWidget\n"
"{\n"
"    alternate-background-color:blue;\n"
"    background:yellow\n"
"}")
        self.infoWidget.setObjectName("infoWidget")
        self.horizontalLayout_2.addWidget(self.infoWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)

        self.retranslateUi(Downloader)
        self.infoWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Downloader)

    def retranslateUi(self, Downloader):
        _translate = QtCore.QCoreApplication.translate
        Downloader.setWindowTitle(_translate("Downloader", "Form"))
import res.resource_rc
