# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/download_config.ui'
#
# Created by: PySide6 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet(".QWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QToolButton{\n"
"    border: 1px solid gray;   /* 边框 */\n"
"    font: 290 9pt \"Microsoft YaHei\";\n"
"    border-radius: 3px;   /* 圆角 */\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    border: 1px solid gray;   /* 边框 */\n"
"    font: 290 9pt \"Microsoft YaHei\";\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 3px;   /* 圆角 */\n"
"}\n"
"\n"
"QWidget {\n"
"        font: 9pt \"JetBrains Mono\";\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.urlEdit = QtWidgets.QLineEdit(Dialog)
        self.urlEdit.setObjectName("urlEdit")
        self.horizontalLayout.addWidget(self.urlEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pathLabel = QtWidgets.QLabel(Dialog)
        self.pathLabel.setObjectName("pathLabel")
        self.horizontalLayout_3.addWidget(self.pathLabel)
        self.pathEdit = QtWidgets.QLineEdit(Dialog)
        self.pathEdit.setObjectName("pathEdit")
        self.horizontalLayout_3.addWidget(self.pathEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.modeBox = QtWidgets.QComboBox(Dialog)
        self.modeBox.setObjectName("modeBox")
        self.modeBox.addItem("")
        self.modeBox.addItem("")
        self.horizontalLayout_2.addWidget(self.modeBox)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "url "))
        self.pathLabel.setText(_translate("Dialog", "path"))
        self.label_2.setText(_translate("Dialog", "mode"))
        self.modeBox.setItemText(0, _translate("Dialog", "SimpleAnalyze"))
        self.modeBox.setItemText(1, _translate("Dialog", "RecursiveAnalyze"))
