# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/state_widget.ui'
#
# Created by: PySide6 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_stateWidget(object):
    def setupUi(self, stateWidget):
        stateWidget.setObjectName("stateWidget")
        stateWidget.setWindowModality(QtCore.Qt.NonModal)
        stateWidget.resize(540, 85)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(stateWidget.sizePolicy().hasHeightForWidth())
        stateWidget.setSizePolicy(sizePolicy)
        stateWidget.setMinimumSize(QtCore.QSize(0, 0))
        stateWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        stateWidget.setStyleSheet(".QWidget {\n"
"    font: 9pt \"JetBrains Mono\";\n"
"    border: 1px solid gray;   /* 边框 */\n"
"    border-radius: 3px;   /* 圆角 */\n"
"    border-color: rgb(209, 209, 209);\n"
"}\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(stateWidget)
        self.verticalLayout_3.setContentsMargins(15, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(stateWidget)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(48, 48))
        self.label.setStyleSheet("image: url(:/icon/icon/m3u8.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pathLabel = QtWidgets.QLabel(stateWidget)
        self.pathLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pathLabel.setStyleSheet("font: 9pt \"黑体\";")
        self.pathLabel.setObjectName("pathLabel")
        self.verticalLayout.addWidget(self.pathLabel)
        self.progressBar = QtWidgets.QProgressBar(stateWidget)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 20))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid gray;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color: rgb(230, 230, 230);\n"
"    border-radius: 3px;   /* 圆角 */\n"
"    \n"
"    font: 9pt \"黑体\";\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.0284091, x2:0, y2:0, stop:0.278607 rgba(252, 210, 171, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar, 0, QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(4, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 10)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(stateWidget)
        QtCore.QMetaObject.connectSlotsByName(stateWidget)

    def retranslateUi(self, stateWidget):
        _translate = QtCore.QCoreApplication.translate
        stateWidget.setWindowTitle(_translate("stateWidget", "Form"))
        self.pathLabel.setText(_translate("stateWidget", "path"))
import res.resource_rc
